---
title: "R Notebook"
output: html_notebook
---
#### Clear Environment
```{r}
rm(list = ls())
```

#### Load Libraries
```{r}
library(tidyverse)
library(dplyr)
library(readxl)
library(stringr)
```
# Create Dataset Files
```{r}
craigslist_file <- 'preprocessing/vehicles.csv'
census_median_income_file <- 'preprocessing/census_median_income_2020.csv'
census_variable_list_file <- 'preprocessing/census_median_income_variable_list.csv'
zcta_mapping_file <- 'preprocessing/zcta_zip_city_map.xlsx'
```


#### Import Datasets
```{r}
cars_df <- read.csv(craigslist_file)
```

```{r}
census_df <- read.csv(census_median_income_file, na.strings=c("NA", "NULL"))
cenus_var_df <- read.csv(census_variable_list_file)
zcta_df <- read_xlsx(zcta_mapping_file)
```

#### Inspect 'census_df' first 6 rows
```{r}
head(census_df)
```

#### Subset Census to keep the following variables:
- 'NAME'
- 'S1903_C03_015E' 
- 'S1903_C03_034E'
```{r}
census_df <- census_df[-1,]
census <- subset(census_df, select = c('NAME', 'S1903_C03_015E','S1903_C03_034E'))
census <- census %>%
  rename(zcta = NAME,
         median_income_family = S1903_C03_015E,
         median_income_non_family = S1903_C03_034E
         )

summary(census)
```
```{r}
head(census, 50)
```
#### Change Data Types for Median Columns
```{r}
#unique(census$median_income_family)
```
```{r}
census$median_income_family <- gsub('+', '', 
                               gsub('-', NaN, census$median_income_family))
```

```{r}
head(census)
```

```{r}
census$median_income_family <- as.numeric(census$median_income_family)
census$median_income_non_family <- as.numeric(census$median_income_non_family)

census <- census %>% drop_na()

head(census)
```
```{r}
summary(census)
```


```{r}
census <- separate(census, zcta, c("zcta", "zip_code"), ' ')
```

```{r}
head(census)
```
```{r}
census_m <- merge(census, zcta_df, by.x = 'zip_code', by.y = 'ZIP_CODE')
head(census_m)
```
```{r}
census_clean = subset(census_m, select = c("PO_NAME",
                                           "STATE",
                                           "zip_code",
                                           "median_income_family",
                                           "median_income_non_family"))

census_clean = census_clean %>%
  rename("city" = "PO_NAME",
         "state" = "STATE")
```


