# Script where everything is applied to the scope of ALL files (server and UI)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(DBI, RSQLite, shiny,shinythemes,shinyWidgets, shinyalert,
               DT,forecast,ggplot2,plotly,maps, install = TRUE, update = getOption("pac_update"),)
library(DBI)
library(RSQLite)
library(shiny)
library(shinythemes)
library(shinyWidgets)
library(shinyalert)
library(DT)
library(forecast)
library(ggplot2)
library(plotly)
library(maps)
# library(leaflet)